# FROM python:3.9

# WORKDIR /app
# WORKDIR /app/fastapi

# # RUN apt-get update && apt-get install -y ffmpeg
# COPY app/fastapi /app/fastapi
# COPY requirements.txt /app/requirements.txt
# RUN pip install --no-cache-dir -r /app/requirements.txt
FROM python:3.9

WORKDIR /app
WORKDIR /app/fastapi

# RUN apt-get update && apt-get install -y ffmpeg

# Copy the requirements and install dependencies
COPY requirements.txt /app/requirements.txt/
RUN pip install --no-cache-dir -r /app/requirements.txt

RUN pip install "fastapi[standard]"
# Copy the FastAPI code into the container
COPY ./app/fastapi /app/fastapi/


# Copy the requirements and install dependencies
# COPY requirements.txt /app/requirements.txt

# RUN pip install --no-cache-dir -r /Users/patil/Workspace/VS code/Income_Classification/requirements.txt
# RUN pip install "fastapi[standard]"
# Copy the FastAPI code into the container


# Expose the correct port for Cloud Run
EXPOSE 8000


CMD ["python", "app/fastapi/main.py"]

